name: Python Unittest

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-13, ubuntu-latest]
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Use wabt 1.0.20
        uses: mwilliamson/setup-wabt-action@v3
        with:
          wabt-version: "1.0.35"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        id: tests
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-13'
        env:
          OUTPUT_LOG: test_result_temp.log
          RESULT_LOG: test_result.log
        run: |
          wast2json --version
          python3 -m unittest discover -p test_*.py -s tests > $OUTPUT_LOG 2>&1 || true
          tail -n 3 $OUTPUT_LOG > $RESULT_LOG
          cat $OUTPUT_LOG

      - name: Run tests on Windows
        if: matrix.os == 'windows-latest'
        env:
          OUTPUT_LOG: test_result_temp.log
          RESULT_LOG: test_result.log
        run: |
          wast2json --version
          python -m unittest discover -p test_*.py -s tests > %OUTPUT_LOG% 2>&1 || true
          Get-Content -Path %OUTPUT_LOG% -Tail 3 | Set-Content -Path %RESULT_LOG% -Encoding UTF8
          Get-Content -Path %OUTPUT_LOG% -Encoding UTF8

      - name: Comment on commit
        if: always()
        uses: actions/github-script@v6
        env:
          RESULT_LOG: test_result.log
          OS: ${{ matrix.os }}
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const commit_sha = context.sha;
            const test_result = require('fs').readFileSync(process.env.RESULT_LOG, 'utf8');
            const message = `Test result on ${process.env.OS}:\n\`\`\`\n${test_result}\n\`\`\``;
            github.rest.repos.createCommitComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: commit_sha,
              body: message
            });
