name: Python Unittest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Wabt
        env:
          WABT_VERSION: 1.0.35
        run: |
          wget https://github.com/WebAssembly/wabt/releases/download/${WABT_VERSION}/wabt-${WABT_VERSION}-ubuntu-20.04.tar.gz
          tar -xzf wabt-${WABT_VERSION}-ubuntu-20.04.tar.gz
          echo "$(pwd)/wabt-${WABT_VERSION}/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        id: tests
        env:
          OUTPUT_LOG: test_result_temp.log
          RESULT_LOG: test_result.log
        run: |
          wast2json --version
          python3 -m unittest discover -p test_*.py -s tests > $OUTPUT_LOG 2>&1 || true
          tail -n 3 $OUTPUT_LOG > $RESULT_LOG
          cat $OUTPUT_LOG

      - name: Comment on commit
        if: always()
        uses: actions/github-script@v6
        env:
          RESULT_LOG: test_result.log
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const commit_sha = context.sha;
            const test_result = require('fs').readFileSync(process.env.RESULT_LOG, 'utf8');
            const message = `Test result: ${test_result}`;
            github.rest.repos.createCommitComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: commit_sha,
              body: message
            });
